# Generated by Django 4.2.2 on 2023-06-23 07:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formula', '0001_initial'),
        ('note', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectiveId', models.IntegerField(blank=True)),
                ('objectiveName', models.IntegerField(blank=True)),
                ('keyResultId', models.IntegerField(blank=True)),
                ('keyResultName', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=50)),
                ('regularly', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=50)),
                ('unit', models.CharField(max_length=250)),
                ('condition', models.IntegerField()),
                ('norm', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('result', models.IntegerField(blank=True)),
                ('ratio', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('done', 'done'), ('fail', 'fail'), ('progress', 'progress')], default='progress', max_length=50)),
                ('createBy', models.CharField(max_length=250)),
                ('updateBy', models.CharField(max_length=250)),
                ('createAt', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('formula_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='formula.formula')),
                ('note_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='note.note')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='source.source')),
            ],
            options={
                'db_table': 'Okr',
                'ordering': ['-id'],
            },
        ),
    ]
