# Generated by Django 4.2.2 on 2023-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeCode', models.CharField(max_length=250)),
                ('fullName', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('birthDate', models.CharField(max_length=250)),
                ('phoneNumber', models.CharField(max_length=250)),
                ('emailAddress', models.CharField(max_length=250)),
                ('jobCode', models.CharField(max_length=250)),
                ('jobTitle', models.CharField(max_length=250)),
                ('officerTitle', models.CharField(max_length=250)),
                ('locationAddress', models.CharField(max_length=250)),
                ('organizationNamePath', models.CharField(max_length=250)),
                ('organizationCodePath', models.CharField(max_length=250)),
                ('createAt', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=50)),
                ('dateIn', models.DateTimeField(blank=True, null=True)),
                ('dateOut', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-id'],
            },
        ),
    ]
