# Generated by Django 4.2.2 on 2023-06-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('createBy', models.CharField(max_length=250)),
                ('updateBy', models.CharField(max_length=250)),
                ('createAt', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(blank=True, null=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['-id'],
            },
        ),
    ]
