# Generated by Django 4.2.2 on 2023-06-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('employee', 'employee'), ('CBQL', 'CBQL'), ('TL', 'TL')], default='employee', max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_department', to='department.department')),
            ],
            options={
                'db_table': 'manager',
                'ordering': ['-id'],
            },
        ),
    ]
